build-system: Fix autocomplete error response (#26824)
Resolve error "TypeError: res is not a function"

(cherry picked from commit 31c15e390e8c5f46810bd1e80e5cf40a673a1425)